SPEED_FACTOR = 5

PLAYER_WIDTH = 10
PLAYER_HEIGHT = 10

FRAME_WIDTH = 400
FRAME_HEIGHT = 600
FPS = 30  # 30 frames per second
TIME_GAP_IN_SECONDS = 1/FPS  # gap between successive frames in seconds

OBSTACLE_WIDTH = 80
OBSTACLE_HEIGHT = 10
OBSTACLE_SPEED = 20  # pixels per second
OBSTACLE_ADDITION_PERIOD = 4/SPEED_FACTOR  # seconds between obstacle addition

PLAYER_CHROMOSOME_LENGTH = 87
PLAYER_POINTERS = 3
POINTER_COMBINATIONS = 7
ANGLE_GENE_SIZE = 8
LENGTH_GENE_SIZE = 7
SPEED_GENE_SIZE = 5
DIRECTION_GENE_SIZE = 1
